{
 "title": "Go App Monitoring",
 "tags": [
  "go",
  "prometheus",
  "grafana"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Общее число запросов",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(app_http_requests_total)" }
   ]
  },
  {
   "title": "Число ошибок",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(app_http_errors_total)" }
   ]
  },
  {
   "title": "Активные запросы",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_active_requests" }
   ]
  },
  {
   "title": "Количество запросов по маршрутам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (path) (app_http_requests_total)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Средняя длительность обработки",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(app_http_request_duration_seconds_sum[1m])) / sum(rate(app_http_request_duration_seconds_count[1m]))",
     "legendFormat": "avg duration"
    }
   ]
  },
  {
   "title": "Ошибки по коду ответа",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (status_code) (app_http_errors_total)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Запросы по студентам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum by (student_id) (app_student_requests_total)",
     "legendFormat": "student {{student_id}}"
    }
   ]
  }
 ]
}