#!/usr/bin/env bash
set -euo pipefail

GQLGEN_VERSION="${GQLGEN_VERSION:-v0.17.49}"
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

echo "==> Project directory: $ROOT_DIR"
echo "==> Using gqlgen ${GQLGEN_VERSION}"

go version

mkdir -p graph/generated graph/model

# Bootstrap stubs are needed only before the first gqlgen generation.
# They allow gqlgen to type-check existing resolvers in a clean ZIP archive.
if [[ ! -f graph/model/models_gen.go ]]; then
  cat > graph/model/models_gen.go <<'STUB'
// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.
// Temporary bootstrap stub. It is overwritten by gqlgen generate.
package model

type Task struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
	Done        bool    `json:"done"`
}

type CreateTaskInput struct {
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
}

type UpdateTaskInput struct {
	Title       *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	Done        *bool   `json:"done,omitempty"`
}
STUB
fi

if [[ ! -f graph/generated/generated.go ]]; then
  cat > graph/generated/generated.go <<'STUB'
// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.
// Temporary bootstrap stub. It is overwritten by gqlgen generate.
package generated

import (
	"context"

	"github.com/CyberGeo335/pz11-graphql/graph/model"
)

type ResolverRoot interface {
	Mutation() MutationResolver
	Query() QueryResolver
}

type MutationResolver interface {
	CreateTask(ctx context.Context, input model.CreateTaskInput) (*model.Task, error)
	UpdateTask(ctx context.Context, id string, input model.UpdateTaskInput) (*model.Task, error)
	DeleteTask(ctx context.Context, id string) (bool, error)
}

type QueryResolver interface {
	Tasks(ctx context.Context) ([]*model.Task, error)
	Task(ctx context.Context, id string) (*model.Task, error)
}
STUB
fi

echo "==> Generating gqlgen runtime and GraphQL models"
go run "github.com/99designs/gqlgen@${GQLGEN_VERSION}" generate

echo "==> Synchronizing go.mod/go.sum"
go mod tidy

echo "==> Formatting source files"
gofmt -w server.go graph/*.go graph/generated/*.go graph/model/*.go internal/**/*.go

echo "==> Running tests/build check"
go test ./...

echo ""
echo "Done. Start the API with:"
echo "  go run ./server.go"
echo "Then open:"
echo "  http://localhost:8080/"
